config/routes.rb
Rails.application.routes.draw do
  resources :categories

  resources :widgets

  root 'welcome#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_attached_file :image, :styles => { :original => "210x210#", :thumb => "100x100#", :mini => "64x64#", :nano => "20x20#" }, :default_url => "/assets/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/widget.rb
class Widget < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :excerpt, :description, :seo_title, :seo_keywords, :seo_description, :image)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  # GET /welcome
  def index

  end

end

app/controllers/widgets_controller.rb
class WidgetsController < ApplicationController
  before_action :set_widget, only: [:show, :edit, :update, :destroy]

  # GET /widgets
  # GET /widgets.json
  def index
    @widgets = Widget.all
  end

  # GET /widgets/1
  # GET /widgets/1.json
  def show
  end

  # GET /widgets/new
  def new
    @widget = Widget.new
  end

  # GET /widgets/1/edit
  def edit
  end

  # POST /widgets
  # POST /widgets.json
  def create
    @widget = Widget.new(widget_params)

    respond_to do |format|
      if @widget.save
        format.html { redirect_to @widget, notice: 'Widget was successfully created.' }
        format.json { render :show, status: :created, location: @widget }
      else
        format.html { render :new }
        format.json { render json: @widget.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /widgets/1
  # PATCH/PUT /widgets/1.json
  def update
    respond_to do |format|
      if @widget.update(widget_params)
        format.html { redirect_to @widget, notice: 'Widget was successfully updated.' }
        format.json { render :show, status: :ok, location: @widget }
      else
        format.html { render :edit }
        format.json { render json: @widget.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /widgets/1
  # DELETE /widgets/1.json
  def destroy
    @widget.destroy
    respond_to do |format|
      format.html { redirect_to widgets_url, notice: 'Widget was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_widget
      @widget = Widget.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def widget_params
      params.require(:widget).permit(:name, :description, :stock)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/widgets_helper.rb
module WidgetsHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :excerpt %><br>
    <%= f.text_field :excerpt %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :seo_title %><br>
    <%= f.text_field :seo_title %>
  </div>
  <div class="field">
    <%= f.label :seo_keywords %><br>
    <%= f.text_field :seo_keywords %>
  </div>
  <div class="field">
    <%= f.label :seo_description %><br>
    <%= f.text_field :seo_description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Excerpt</th>
      <th>Description</th>
      <th>Seo title</th>
      <th>Seo keywords</th>
      <th>Seo description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.excerpt %></td>
        <td><%= category.description %></td>
        <td><%= category.seo_title %></td>
        <td><%= category.seo_keywords %></td>
        <td><%= category.seo_description %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Excerpt:</strong>
  <%= @category.excerpt %>
</p>

<p>
  <strong>Description:</strong>
  <%= @category.description %>
</p>

<p>
  <strong>Seo title:</strong>
  <%= @category.seo_title %>
</p>

<p>
  <strong>Seo keywords:</strong>
  <%= @category.seo_keywords %>
</p>

<p>
  <strong>Seo description:</strong>
  <%= @category.seo_description %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/layouts/_brand.html.haml
.row
  .col-lg-12.brand
    = link_to root_path do
      = image_tag "logo-01.svg"

app/views/layouts/_main_nav.html.haml
.container
  %ul.list-inline.main-nav
    %li #{link_to "Планирование", ""}
    %li #{link_to "Каталог компаний", ""}
    %li #{link_to "Идеи и вдохновение", ""}
    %li #{link_to "Статьи", ""}
    %li #{link_to "Свадебный сайт", ""}
    %li #{link_to "Выгодные предложения", ""}

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "danger"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-default{:role => "navigation"}
  .container-fluid
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      %button.navbar-toggle.collapsed{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
    / Collect the nav links, forms, and other content for toggling
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li
          %p.nav.navbar-text
            Ваш город:
            %a{:href => "#"} Москва
      %ul.nav.navbar-nav.navbar-right
        %li
          %a{:href => "#"} Регистрация
        %li
          %a{:href => "#"} Войти
        %li
          %a{:href => "#"} Для владельцев бизнеса

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Wedville
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    = stylesheet_link_tag :application, :media => "all"
    = javascript_include_tag :application
    = csrf_meta_tags
  %body
    = render 'layouts/navbar'
    = render 'layouts/brand'
    = render 'layouts/main_nav'
    = render 'layouts/messages'
    = yield

app/views/welcome/_main_content.html.haml
.row
  .col-lg-9
    %p.grid-header Товары и услуги
    .row.grid
      .col-lg-4.col-md-3.col-sm-4.col-xs-4
        = image_tag "http://placehold.it/210x210", :class => 'img-responsive'
        %p.category-caption Свадебные наряды и аксессуары
      .col-lg-4.col-md-3.col-sm-4.col-xs-4
        = image_tag "http://placehold.it/210x210", :class => 'img-responsive'
        %p.category-caption Свадебные наряды и аксессуары
      .col-lg-4.col-md-3.col-sm-4.col-xs-4
        = image_tag "http://placehold.it/210x210", :class => 'img-responsive'
        %p.category-caption Свадебные наряды и аксессуары
      .col-lg-4.col-md-3.col-sm-4.col-xs-4
        = image_tag "http://placehold.it/210x210", :class => 'img-responsive'
        %p.category-caption Свадебные наряды и аксессуары
      .col-lg-4.col-md-3.col-sm-4.col-xs-4
        = image_tag "http://placehold.it/210x210", :class => 'img-responsive'
        %p.category-caption Свадебные наряды и аксессуары
      .col-lg-4.col-md-3.col-sm-4.col-xs-4
        = image_tag "http://placehold.it/210x210", :class => 'img-responsive'
        %p.category-caption Свадебные наряды и аксессуары
      .col-lg-4.col-md-3.col-sm-4.col-xs-4
        = image_tag "http://placehold.it/210x210", :class => 'img-responsive'
        %p.category-caption Свадебные наряды и аксессуары
      .col-lg-4.col-md-3.col-sm-4.col-xs-4
        = image_tag "http://placehold.it/210x210", :class => 'img-responsive'
        %p.category-caption Свадебные наряды и аксессуары
  .col-lg-3.hidden-md.hidden-sm.hidden-xs
    %p.grid-header Присоединяйтесь
    .join-cell
      %p
        %strong Спланируйте свою свадьбу:
      %input.form-control{:placeholder => "mail@mail.com"}
      %p
        %button.btn.btn-success{:type => "button"} Зарегистрироваться
      %p
        Зарегистрированны? 
        =link_to "Войдите", root_path

app/views/welcome/_main_search.html.haml
.main-search
  .well
    .row
      .col-lg-5.col-md-5.col-sm-4
        %select.form-control
          %option{:value => 'Свадебные наряды и аксессуары'}
            Свадебные наряды и аксессуары
      .col-lg-5.col-md-5.col-sm-4
        %select.form-control
          %option{:value => 'Москва'}
            Москва
      .col-lg-2.col-md-2.col-sm-4
        %button.btn.btn-info{:type => "button"} Найти

app/views/welcome/index.html.haml
.container{:style => "max-width:960px"}
  = render 'main_search'
  = render 'main_content'

app/views/widgets/_form.html.erb
<%= form_for(@widget) do |f| %>
  <% if @widget.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@widget.errors.count, "error") %> prohibited this widget from being saved:</h2>

      <ul>
      <% @widget.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :stock %><br>
    <%= f.number_field :stock %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/widgets/edit.html.erb
<h1>Editing widget</h1>

<%= render 'form' %>

<%= link_to 'Show', @widget %> |
<%= link_to 'Back', widgets_path %>

app/views/widgets/index.html.erb
<h1>Listing widgets</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Stock</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @widgets.each do |widget| %>
      <tr>
        <td><%= widget.name %></td>
        <td><%= widget.description %></td>
        <td><%= widget.stock %></td>
        <td><%= link_to 'Show', widget %></td>
        <td><%= link_to 'Edit', edit_widget_path(widget) %></td>
        <td><%= link_to 'Destroy', widget, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Widget', new_widget_path %>

app/views/widgets/new.html.erb
<h1>New widget</h1>

<%= render 'form' %>

<%= link_to 'Back', widgets_path %>

app/views/widgets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @widget.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @widget.description %>
</p>

<p>
  <strong>Stock:</strong>
  <%= @widget.stock %>
</p>

<%= link_to 'Edit', edit_widget_path(@widget) %> |
<%= link_to 'Back', widgets_path %>